"""Add column indexing

Revision ID: 0d7cf6acc07f
Revises: 22da09c6f739
Create Date: 2021-11-13 15:51:13.297690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0d7cf6acc07f"
down_revision = "22da09c6f739"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("houses", sa.Column("codename", sa.String(length=16), nullable=True))

    conn = op.get_bind()
    res = conn.execute("SELECT id, nama FROM houses").fetchall()
    for id, name in res:
        codename = name.split()[-1].lower()
        conn.execute("UPDATE houses SET codename = (%s) WHERE id = (%s)", codename, id)

    op.create_index(op.f("ix_houses_codename"), "houses", ["codename"], unique=False)
    op.create_index(
        op.f("ix_students_username"), "students", ["username"], unique=False
    )
    op.alter_column("houses", "codename", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_students_username"), table_name="students")
    op.drop_index(op.f("ix_houses_codename"), table_name="houses")
    op.drop_column("houses", "codename")
    # ### end Alembic commands ###
