"""Bump twitter char limit

Revision ID: 22da09c6f739
Revises: 175b53352d7d
Create Date: 2021-11-13 10:52:31.288160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22da09c6f739'
down_revision = '175b53352d7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'twitter',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=32),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'twitter',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)
    # ### end Alembic commands ###
