"""Add stories

Revision ID: 52b2cb0c0545
Revises: a052cc7b8676
Create Date: 2021-10-31 10:40:39.277634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52b2cb0c0545'
down_revision = 'a052cc7b8676'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('foto', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('students', 'nama',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'nama',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_table('stories')
    # ### end Alembic commands ###
