"""Initial

Revision ID: 550a7843a982
Revises: 
Create Date: 2021-09-25 21:23:20.359679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '550a7843a982'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('houses',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('nama', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('npm', sa.Integer(), nullable=True),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('jurusan', sa.String(length=32), nullable=False),
    sa.Column('ttl', sa.String(length=100), nullable=False),
    sa.Column('hobi', sa.String(length=50), nullable=False),
    sa.Column('twitter', sa.String(length=16), nullable=True),
    sa.Column('line', sa.String(length=50), nullable=True),
    sa.Column('instagram', sa.String(length=32), nullable=True),
    sa.Column('karya', sa.JSON(), nullable=True),
    sa.Column('foto_diri', sa.Text(), nullable=False),
    sa.Column('video_diri', sa.Text(), nullable=False),
    sa.Column('house', sa.Integer(), nullable=True),
    sa.Column('house_led', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['house'], ['houses.id'], name='fk_students_houses_id_house'),
    sa.ForeignKeyConstraint(['house_led'], ['houses.id'], name='fk_students_houses_id_house_led'),
    sa.PrimaryKeyConstraint('npm')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    op.drop_table('houses')
    # ### end Alembic commands ###
