"""Add about me on db

Revision ID: 5fcd4f779a6a
Revises: 3aa8d47393fb
Create Date: 2021-10-31 13:52:28.974930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fcd4f779a6a'
down_revision = '3aa8d47393fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('about', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'about')
    # ### end Alembic commands ###
