"""Mark almost all field as optional

Revision ID: 6de34633da3d
Revises: ec380ae57402
Create Date: 2021-10-07 21:58:16.801458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6de34633da3d'
down_revision = 'ec380ae57402'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'jurusan',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('students', 'ttl',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('students', 'hobi',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('students', 'foto_diri',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('students', 'video_diri',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'video_diri',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('students', 'foto_diri',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('students', 'hobi',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('students', 'ttl',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('students', 'jurusan',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    # ### end Alembic commands ###
