"""Add missing fields

Revision ID: a052cc7b8676
Revises: fe212d1dcec7
Create Date: 2021-10-28 18:41:12.312150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a052cc7b8676"
down_revision = "fe212d1dcec7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("students", sa.Column("message", sa.Text(), nullable=True))
    op.add_column("students", sa.Column("interests", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("students", "interests")
    op.drop_column("students", "message")
    # ### end Alembic commands ###
