"""Add SIG and Competitions

Revision ID: ec380ae57402
Revises: 550a7843a982
Create Date: 2021-10-07 21:37:57.001450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec380ae57402'
down_revision = '550a7843a982'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitions',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('nama', sa.String(length=160), nullable=False),
    sa.Column('foto', sa.Text(), nullable=True),
    sa.Column('link', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sigs',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('nama', sa.String(length=160), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('foto', sa.Text(), nullable=True),
    sa.Column('is_it_interest', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sigs')
    op.drop_table('competitions')
    # ### end Alembic commands ###
