"""Add username field

Revision ID: fe212d1dcec7
Revises: 6de34633da3d
Create Date: 2021-10-27 10:41:49.065526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fe212d1dcec7"
down_revision = "6de34633da3d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "students", sa.Column("username", sa.String(length=128), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("students", "username")
    # ### end Alembic commands ###
